export { recognizeText, recognizeToSearchablePdf } from './OcrService'
export type { OcrResult } from './OcrService'
export { categorizeDocument, DOCUMENT_TYPES } from './categorize'
export type { DocumentType } from './categorize'
export { extractCaseNumber } from './extractFields'
